### ISSUE TITLE
ENOENT No such file or directory on Windows

### ISSUE THREAD

**Issue by carneirocarlos** [arboleya/diverge#2]
I am having a error executing a diverge routine on Windows that is working on mac os, attached is a sample project to simulate that, just do "npm install" and "npm run diverge" and you will see the error:

> diverge-test@1.0.0 diverge C:\Projeto\AlphaTheory\diverge-test
> env=browser diverge -f sample.txt result.txt

/c/Projeto/AlphaTheory/diverge-test/node_modules/.bin
[diverge-test.zip](https://github.com/arboleya/diverge/files/911814/diverge-test.zip)
/diverge: line 1: ../diverge/bin/diverge: No such file or directory

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "diverge"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! file C:\WINDOWS\system32\cmd.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! diverge-test@1.0.0 diverge: `env=browser diverge -f sample.txt result.txt`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the diverge-test@1.0.0 diverge script 'env=browser diverge -f sample.txt result.txt'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the diverge-test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     env=browser diverge -f sample.txt result.txt
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs diverge-test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls diverge-test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projeto\AlphaTheory\diverge-test\npm-debug.log
[diverge-test.zip](https://github.com/arboleya/diverge/files/911813/diverge-test.zip)

**Comment by arboleya** [comment]
Apparently you need to set `env` vars differently in windows.

Instead of this:

````json
"diverge": "env=browser diverge -f sample.txt result.txt"
````

You'll need to use something like this:

````json
"diverge": "cmd /V /C \"set env=browser&& diverge -f sample.txt result.txt\""
````

**Note:** Apparently, you cannot add a `space` before the `&&` as well, otherwise it will fail again.

For more info: 
https://superuser.com/questions/223104/setting-environment-variable-for-just-one-command-in-windows-cmd-exe

**Comment by carneirocarlos** [comment]
For anyone who's interested, using Diverge programmatically is a good way to have it working without using env vars to make it Multiplatform.

Here is a script that can be executed like this on both windows and macos:
node atdiverge env=envvarvalue

```
#!/usr/bin/env node

var diverge = require('diverge');

var env = 'default_env'

process.argv.forEach(function (val, index, array) {

    if (val != null && val != undefined && val != "" &&
        val.substring(0, 4) == "env=") {

        env = val.split("=")[1];
        console.log('ATDiverge env = ' + env)
    }

});

diverge('input.html', 'output.html', {env: env}, {force: true});
```
